"""add creator_profiles timezone

Revision ID: 4fa5cea5c968
Revises: e7f16d584e97
Create Date: 2026-08-06 00:04:20.686243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa5cea5c968'
down_revision: Union[str, Sequence[str], None] = 'e7f16d584e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_profiles', 'timezone')
    # ### end Alembic commands ###
